# Generated by Django 2.1.3 on 2018-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.IntegerField()),
                ('stop_name', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.IntegerField()),
                ('fake_count', models.IntegerField()),
            ],
        ),
    ]
