# Generated by Django 2.0.2 on 2018-11-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wth_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fake_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_telegram_id',
            field=models.IntegerField(unique=True),
        ),
    ]
