# Generated by Django 2.0.2 on 2018-11-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wth_base', '0002_auto_20181123_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user_telegram_id',
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wth_base.User'),
            preserve_default=False,
        ),
    ]
