# Generated by Django 2.1.3 on 2018-11-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wth_base', '0004_stop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
